const defaultBSWords = {
    tr: [
        "aile",
        "ailesine",
        "akademi",
        "akademik",
        "akademisi",
        "alanında uzman",
        "anahtar başarı faktörü",
        "analitik",
        "bağlantılarım",
        "bakış açısı",
        "bakış açıları",
        "başarı",
        "başarı hikayesi",
        "başarıyla",
        "başladığımı",
        "bekliyorum",
        "bildirmek isterim",
        "bildirmekten",
        "birlikte büyüyoruz",
        "bitirdim",
        "bulduğum",
        "buldum",
        "bulunuyorum",
        "büyük",
        "çalışmaktan",
        "çalışmaya",
        "çevik",
        "çözüm odaklı",
        "çözüm üretmek",
        "daha gidecek çok yolumuz var",
        "değer katmaya geldik",
        "değerli",
        "deneyim",
        "devam",
        "dijital dönüşüm",
        "dinamik",
        "disiplin",
        "dönüştürücü",
        "duyurmaktan",
        "duyuyorum",
        "düşünebilen",
        "ediyorum",
        "ekibine",
        "ekibimizin bir parçası",
        "ekip arkadaşlarıma",
        "ekosistem",
        "ekosistemimiz",
        "eleştirel",
        "enerji",
        "enerjik",
        "entegrasyon",
        "esnek çalışma saatleri",
        "etki",
        "etkinliğinde",
        "etkinliklerimizde",
        "farkındalık",
        "fark yaratmak",
        "fırsat",
        "fırsatı",
        "gelecek",
        "geleceği inşa ediyoruz",
        "gelişim",
        "gelişmeye",
        "gelişmeyi",
        "geliştirici",
        "geliştirdim",
        "geliştirdik",
        "geliştirdiğimiz",
        "geliştirmek",
        "gerçekleşirdik",
        "gerçekten",
        "geri sayım başladı",
        "girişimci",
        "girişimcilik",
        "global",
        "güçlü",
        "gurur duyuyorum",
        "gururla",
        "gururunu",
        "hak kazandığımı",
        "hak kazandık",
        "hak kazandım",
        "harika",
        "hedef",
        "hedefliyorum",
        "hedef odaklı",
        "hemen başvur",
        "heyecan",
        "heyecanla",
        "heyecanlıyım",
        "hissediyorum",
        "hikayesi",
        "hızlandırıcı",
        "ik",
        "ileri",
        "iletişim becerileri",
        "iletişim yetenekleri",
        "ilham",
        "ilham verici bir gün",
        "inovasyon",
        "inovatif",
        "insan kaynakları",
        "isterim",
        "istiyorum",
        "iş birliği",
        "iş dünyası",
        "iş geliştirme",
        "kaldıraç",
        "kapsayıcı",
        "kariyer",
        "katılacağımı",
        "katıldım",
        "katılımcılarımıza",
        "katılmaktan",
        "katkı sağlamak",
        "katma değer",
        "kendini geliştirmeye açık",
        "kendimi geliştirmeye",
        "kendimi geliştirdiğim",
        "kişisel gelişim",
        "kilometre taşı",
        "kilometre taşını",
        "konfor alanı",
        "koordinasyon",
        "kurumsal kimlik",
        "kutlarım",
        "lider",
        "liderler",
        "liderlik",
        "limitleri zorluyoruz",
        "maratonu",
        "market",
        "memnuniyet",
        "memnunum",
        "mentorluk",
        "motivasyon",
        "motive",
        "mutluluk",
        "mutluluğunu",
        "müşteri odaklı",
        "network",
        "onurluyum",
        "optimizasyon",
        "organizasyon",
        "öğrendiklerim",
        "öğrenmeye",
        "öğrendiğim",
        "ölçeklenebilir",
        "ortak bir noktada",
        "ortak bir zeminde",
        "paha biçilemez",
        "paydaş",
        "paydaşları",
        "paydaşlarımız",
        "paydaşlarımıza",
        "paydaşlarımızla",
        "paylaşmak",
        "paylaşmaktan",
        "pazar",
        "performans",
        "planlama",
        "potansiyel",
        "proaktif",
        "programını",
        "sabırsızlanıyorum",
        "sabırsızlıkla",
        "sağlayabilmekten",
        "samimi",
        "samimiyetle",
        "şanslı",
        "şanslıyım",
        "sektöre yön veren",
        "sektör lideri",
        "sertifika",
        "sertifikamı",
        "sertifikaya",
        "sinerji",
        "sizinle",
        "sizlere",
        "sizlerle",
        "sonuç odaklı",
        "sorumluluk",
        "startup",
        "strateji",
        "stratejileri",
        "stratejik",
        "sürekli öğrenmek",
        "sürdürülebilir",
        "sürdürülebilirlik",
        "takım çalışmasına yatkın",
        "tamamladığım",
        "tamamladığımı",
        "tamamladım",
        "tamamladık",
        "tamamlamış",
        "tamamlayarak",
        "tebrik ederim",
        "tebrikler",
        "teknoloji",
        "trend",
        "trendleri",
        "tutku odaklı",
        "uçtan uca",
        "uzmanlık",
        "üretken",
        "üretmek",
        "üretmeye", 
        "verimlilik",
        "veriye dayalı",
        "vizyon",
        "yakaladık",
        "yapay zeka",
        "yaptım",
        "yaratıcı",
        "yaşıyorum",
        "yatırım",
        "yeni bir serüvene",
        "yeni şeyler",
        "yenilikçi",
        "yer almaktan",
        "yetenek programı",
        "yetkinlik",
        "yetkinliklerim",
        "yol haritası",
        "yolculukta",
        "yolculuk",
        "yolculuğumda",
        "yolculuğumuz",
        "yolculuğumuzda",
        "yönetici",
        "yönetim",
        "yönetim kurulu başkanı",
        "yürütülen",
        "zirve",
        "zirvesi"
    ],
    en: [
        "#hiring",
        "accelerator",
        "acquisition",
        "advisory",
        "agile",
        "ai",
        "AI-driven",
        "alignment",
        "analytics",
        "ARR",
        "attending",
        "bandwidth",
        "beyond",
        "board",
        "breaking barriers",
        "bootstrapped",
        "career",
        "certificate",
        "certification",
        "chapter",
        "circle back",
        "cloud",
        "cloud-native",
        "co-founder",
        "coaching",
        "completed",
        "comprehensive",
        "congrats",
        "congratulations",
        "connections",
        "continuous learning",
        "contribute",
        "contributing",
        "contribution",
        "coordination",
        "critical thinking",
        "customer success",
        "CX",
        "data science",
        "data-driven",
        "dear connections",
        "deep dive",
        "deliverables",
        "delighted",
        "disruption",
        "disruptive",
        "due diligence",
        "ecosystem",
        "energetic",
        "entrepreneur",
        "entrepreneurship",
        "environment",
        "excited",
        "exit",
        "experience",
        "experiences",
        "experienced",
        "expertise",
        "explore",
        "flexible",
        "founder",
        "funding",
        "game changer",
        "game changing",
        "global",
        "grateful",
        "gratitude",
        "growth",
        "growth hacking",
        "happy",
        "hiring",
        "holistic",
        "hr",
        "humbled and honored",
        "human resources",
        "hybrid",
        "ideathon",
        "improving",
        "incredible",
        "incubator",
        "inspiration",
        "inspiring",
        "inspired",
        "innovation",
        "innovative",
        "IPO",
        "it was great",
        "journey",
        "leader",
        "leaders",
        "leadership",
        "leverage",
        "linkedin",
        "low-hanging fruit",
        "machine learning",
        "market",
        "marketing",
        "meaningful",
        "mentorship",
        "milestone",
        "mind set",
        "mindset",
        "mission",
        "ML",
        "move the needle",
        "MRR",
        "network",
        "NLP",
        "onboarding",
        "open to work",
        "opportunity",
        "paradigm shift",
        "pitch",
        "pivot",
        "pleased",
        "PMF",
        "private",
        "privilege",
        "problem solver",
        "product",
        "product-first",
        "product-market fit",
        "production",
        "productive",
        "professional",
        "proud",
        "raise",
        "remote",
        "revenue",
        "robust",
        "SaaS",
        "scalable",
        "scale",
        "seed funding",
        "series A",
        "series B",
        "skills",
        "started",
        "success",
        "successful",
        "successfully",
        "synergistic",
        "synergy",
        "talent program",
        "think outside the box",
        "thought leader",
        "to announce",
        "to attend",
        "to be part of",
        "to have",
        "to share",
        "to take part",
        "touch base",
        "transform",
        "transformation",
        "transformative",
        "truly",
        "ui",
        "unicorn",
        "unique",
        "unlocking potential",
        "ux",
        "valuation",
        "vision",
        "workflow"
    ]
};

// Eklentide kullanmak için tüm kelimeleri tek bir listede topluyoruz
const allDefaultBSWords = Object.values(defaultBSWords).flat();